apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: "2019-08-29T19:21:17Z"
  name: nginx-configuration
  namespace: ingress-space
  resourceVersion: "38018"
  selfLink: /api/v1/namespaces/ingress-space/configmaps/nginx-configuration
  uid: 2c90125e-ca92-11e9-905e-42010a8c0019
